SELECT A.B1_ALT_ID [Record ID]
     , B1_APPL_STATUS
     ,B.G6_ACT_TYP [Inspection Type], 
     FORMAT(B.G6_ACT_DD,'MM/dd/yyyy') [Schedule Date], 
     FORMAT(G6_COMPL_DD, 'MM/dd/yyyy') [Inspection Date]

FROM B1PERMIT A

LEFT OUTER JOIN G6ACTION B  ON

B.B1_PER_ID1 = A.B1_PER_ID1 AND
B.B1_PER_ID2 = A.B1_PER_ID2 AND
B.B1_PER_ID3 = A.B1_PER_ID3 AND

B.SERV_PROV_CODE = A.SERV_PROV_CODE

WHERE 

--(B.G6_COMPL_DD >= '03/10/2023' AND B.G6_COMPL_DD <= '03/13/2023' or
B.G6_ACT_DD >= '03/10/2023' AND B.G6_ACT_DD <= '03/13/2023'


AND B.G6_ACT_TYP LIKE 'BLD-Comprehensive-BLD-EL-ME-PL-GAS-Final'
AND A.REC_STATUS ='A'

ORDER BY G6_ACT_TYP ASC