SELECT   
A.B1_APP_TYPE_ALIAS [Application Type], COUNT(*) AS 'Issued Permits' 


FROM B1PERMIT A 

LEFT OUTER JOIN 

GPROCESS_HISTORY B ON

B.B1_PER_ID1 = A.B1_PER_ID1 AND
B.B1_PER_ID2 = A.B1_PER_ID2 AND
B.B1_PER_ID3 = A.B1_PER_ID3 AND



B.SERV_PROV_CODE = A.SERV_PROV_CODE

LEFT OUTER JOIN G3DPTTYP C ON 

C.R3_AGENCY_CODE = B.SD_AGENCY_CODE AND
C.R3_BUREAU_CODE = B.SD_BUREAU_CODE AND
C.R3_DIVISION_CODE = B.SD_DIVISION_CODE AND
C.R3_SECTION_CODE= B.SD_SECTION_CODE AND
C.R3_GROUP_CODE = B.SD_GROUP_CODE AND
C.R3_OFFICE_CODE = B.SD_OFFICE_CODE AND

C.SERV_PROV_CODE = B.SERV_PROV_CODE 


WHERE B.SD_APP_DD >= '10/01/2022' AND B.SD_APP_DD <= '02/27/2023'

AND SD_APP_DES LIKE 'Issued'
AND (  B1_MODULE_NAME LIKE 'Planning' OR B1_MODULE_NAME LIKE 'Enforcement' OR  B1_MODULE_NAME LIKE 'Building')
AND B1_APPL_STATUS NOT LIKE '%Withdrawn%'
AND B1_ALT_ID NOT LIKE '%TMP%'
AND A.B1_ALT_ID NOT LIKE '%CMP%'
AND A.B1_ALT_ID NOT LIKE '%BLDLP%'
AND A.B1_ALT_ID NOT LIKE '%BLDCO%'




GROUP BY A.B1_APP_TYPE_ALIAS


ORDER BY A.B1_APP_TYPE_ALIAS ASC