SELECT GF_COD, TRAN_DATE, TRAN_AMOUNT, ACTION



FROM

ACCOUNTING_AUDIT_TRAIL

WHERE TRAN_DATE >= '2019-01-01'AND 

/*
( GF_COD = 'TR-TR-MITNC'  OR 
  GF_COD = 'TR-TR-MITCBD' OR 
  GF_COD = 'TR-TR-MITCE'  OR 
  GF_COD = 'TR-TR-MITINT' OR 
  GF_COD = 'TR-TR-MITUNI' OR 
  GF_COD = 'TR-TR-MITWSH' ) 
*/
TRAN_AMOUNT LIKE '%53321%'

